spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  application:
    name: salespage-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    properties:
      sasl.mechanism: SCRAM-SHA-512
      security.protocol: SASL_PLAINTEXT
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="bizfly-7-413-admin" password="admin123";
    topic:
      replication-factor: ${KAFKA_REPLICATION_FACTOR:1}
      num-partitions: ${KAFKA_NUM_PARTITIONS:3}
    producer:
      acks: all
      retries: 1000
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      properties:
        specific.avro.reader: true
      template:
        default-topic: test
    consumer:
      enable-auto-commit: true
      properties:
        request:
          timeout:
            ms: 120000
        specific.avro.reader: true
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      group-id: "bizfly-7-413-ProductTransaction"
  data:
    mongodb:
      uri: ${MONGODB_URI}
  aop:
    proxy-target-class: true
  main:
    allow-bean-definition-overriding: true

server:
  port: ${PORT}

jwt:
  publicKey: ${JWT_PUBLIC_KEY}
  privateKey: ${JWT_PRIVATE_KEY}


