spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  application:
    name: salespage-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:cluster001.kas.bfcplatform.vn:9094}
    properties:
      sasl.mechanism: SCRAM-SHA-512
      security.protocol: SASL_PLAINTEXT
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME:bizfly-7-453-admin}" password="${KAFKA_PASSWORD:admin123}";
    topic:
      replication-factor: ${KAFKA_REPLICATION_FACTOR:1}
      num-partitions: ${KAFKA_NUM_PARTITIONS:3}
    producer:
      acks: all
      retries: 1000
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      template:
        default-topic: test
    consumer:
      enable-auto-commit: true
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: "bizfly-7-453-ProductTransaction"
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://lam:12345@db-salespage.h9186rq.mongodb.net/db-salespage}
  aop:
    proxy-target-class: true
  main:
    allow-bean-definition-overriding: true
  springdoc:
    swagger-ui:
      path:/swagger-ui.html
debug: ${DEBUG:debug}
logging:
  config : classpath:log.xml
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

server:
  port: ${PORT:8080}

google:
  api:
    url: ${DRIVER_URI}

jwt:
  secret : ${JWT_SECRET:abajihi3hi234hihi3f09acn}
  publicKey: ${JWT_PUBLIC_KEY}
  privateKey: ${JWT_PRIVATE_KEY}
  token-expire-time : ${JWT_TOKEN_EXPIRE_TIME:7200000}

